### ISSUE TITLE
Cannot build with ghc-8.4.3

### ISSUE THREAD

**Issue by l29ah** [pontarius/pontarius-xmpp#114]
```
source/Network/Xmpp/Types.hs:738:10: error:
    • No instance for (Semigroup StreamFeatures)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid StreamFeatures’
    |
738 | instance Monoid StreamFeatures where
    |          ^^^^^^^^^^^^^^^^^^^^^
```
