### PR TITLE
Patches for compiling on a recent stack

### PR DESCRIPTION
**Pull request by jmazon**
Hi,

I've had to patch a few things to get pontarius-xmpp to build on a recent stack, so I figure it can be useful to others.

Mostly this entails:

* Cabal 3.0 (I suppose it's 2.0-compatible, but haven't tested)
* MonadFail (GHC >= 8.8)
* network >= 3.0
* lens-family >= 2.0

This is really just me updating stuff until it compiles, I haven't really
used it yet.

I specifically don't pretend to understand what that codeblock in Setup.hs
tries to achieve.  Or why it ran just fine without the line I removed in
Doctest.hs.

I'm not sure what the compatibility policy is for this project, so merge with care if you're interested.

### CODE REVIEW

**Comment by l29ah** [comment]
Results in this on 8.6.5:
```
dist/setup/setup.hs:16:47: error:
    Module
    ‘Distribution.Types.MungedPackageName’
    does not export
    ‘encodeCompatPackageName’
   |
16 | import Distribution.Types.MungedPackageName ( encodeCompatPackageName )
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jmazon** [comment]
Yes, I suppose I went straight from the status quo to my 8.8 or 8.10. I actually don't remember which: I've drifted away from this project and moved closer to implementing my own library for this.

If you can provide an 8.6-targetting diff (CPP, I suppose), I suppose they'd appreciate it here.  Feel free to refork me if it makes your life easier!

**Comment by l29ah** [comment]
Reverting changes in `Setup.hs`, `source/Network/Xmpp/Concurrent/Presence.hs`, and `source/Network/Xmpp/IM/PresenceTracker.hs` makes it build on ghc-8.6.5.

**Comment by l29ah** [comment]
I've took over the maintainership of this package (now it lives at https://github.com/l29ah/pontarius-xmpp), and integrated the ghc-8.6-compatible portion of this pull request, thank you for your work!

I would like to also get all the other stuff to be ghc-8.{8,10}-compatible, but i'm not sure how to do it in a backwards-compatible way. A CPP check as discussed in https://stackoverflow.com/questions/28292476/ghc-version-check-in-code seems to be appropriate, but after looking at your changes to `Setup.hs` it seems to me you also touched all the warnings that should also apply to earlier versions, so i'm not sure if i should blindly add the gates to your patches. It would be really nice if you could supply the code with checks that i can test and release on hackage.
